name: Run Flask App and Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask discord.py requests gunicorn

    - name: Run Flask app
      run: |
        nohup gunicorn app:app --bind 0.0.0.0:8000 &
        nohup python bot.py &
